// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJDxJXszMZS_PmkG6Baja7RC8FEIADd8o',
    appId: '1:786794204952:web:077a37bbdc9c7cc8c3d86d',
    messagingSenderId: '786794204952',
    projectId: 'notizenapp-82537',
    authDomain: 'notizenapp-82537.firebaseapp.com',
    databaseURL:
        'https://notizenapp-82537-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notizenapp-82537.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8MVj0D2QiVYC_HO9Yn6hJG2RSj8IR1u0',
    appId: '1:471441564519:android:8f6f81842723b83c6305c2',
    messagingSenderId: '471441564519',
    projectId: 'notis-2dee0',
    storageBucket: 'notis-2dee0.firebasestorage.app',
    androidClientId:
        '471441564519-ho80krlsqfnrepjffekbtpvgmjqm0aeh.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlA8ZCty32nNAwOxg6T2TSlHNIlqnXsrw',
    appId: '1:471441564519:ios:5255a010c86d17696305c2',
    messagingSenderId: '471441564519',
    projectId: 'notis-2dee0',
    storageBucket: 'notis-2dee0.firebasestorage.app',
    iosClientId:
        '471441564519-852ue7rbppu18f584g5tnrh0j28pege5.apps.googleusercontent.com',
    iosBundleId: 'de.notis.app',
  );
}
