// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJDxJXszMZS_PmkG6Baja7RC8FEIADd8o',
    appId: '1:786794204952:web:077a37bbdc9c7cc8c3d86d',
    messagingSenderId: '786794204952',
    projectId: 'notizenapp-82537',
    authDomain: 'notizenapp-82537.firebaseapp.com',
    databaseURL:
        'https://notizenapp-82537-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notizenapp-82537.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqdKa0diSYjT6BBSDDwwfktr2cKpdh94',
    appId: '1:786794204952:android:a11fad72b213039ec3d86d',
    messagingSenderId: '786794204952',
    projectId: 'notizenapp-82537',
    databaseURL:
        'https://notizenapp-82537-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notizenapp-82537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDtjyolydXi6__x6ChVWmMtYyx5r3TDeE',
    appId: '1:786794204952:ios:a4ccaafa3f6db81bc3d86d',
    messagingSenderId: '786794204952',
    projectId: 'notizenapp-82537',
    databaseURL:
        'https://notizenapp-82537-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notizenapp-82537.firebasestorage.app',
    androidClientId:
        '786794204952-5us82qsdrsatnm461m9es7am9qq3n1qu.apps.googleusercontent.com',
    iosClientId:
        '786794204952-rj8nqncl2ipqeet49urjrpb0er6t4bkb.apps.googleusercontent.com',
    iosBundleId: 'com.betternotes.betternotes',
  );
}
